name: martin_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  flutter_staggered_grid_view: ^0.3.2
  carousel_pro: ^1.0.0
  image_fade: ^0.2.1
  auto_animated: ^3.0.0
  modal_progress_hud: ^0.1.3
  form_validator: ^0.1.5
  dio: 3.0.10
  get: 4.1.4
  firebase_core: ^1.1.1
  shimmer: 2.0.0
  google_fonts: ^1.1.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

