name: martin_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  flutter_staggered_grid_view: ^0.3.2
  carousel_pro: ^1.0.0
  image_fade: ^0.2.1
  auto_animated: ^3.0.0
  modal_progress_hud: ^0.1.3
  form_validator: ^0.1.5
  google_fonts: ^2.1.0
  json_store: ^2.0.0-nullsafety.0
  dio: 4.0.0
  get: 4.1.4 
  shimmer: 2.0.0
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  google_sign_in: ^5.0.3
  # flutter_facebook_auth: ^3.3.3
  
  

  

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts: 
    - family: Caslon
      fonts: 
        - asset: assets/fonts/Caslon.ttf
    - family: AvenirBold
      fonts: 
        - asset: assets/fonts/AvenirBold.otf
    - family: SultanNahia
      fonts: 
        - asset: assets/fonts/SultanNahia.ttf
    - family: Avenir
      fonts: 
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf
    - family: Nunito
      fonts: 
        - asset: assets/fonts/Nunito.ttf
          weight: 700
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat.ttf

